--BOARD
--CREATE TABLE BOARD.BOARD (
--	ID VARCHAR2(18 CHAR) NOT NULL,
--	TITLE VARCHAR2(200 CHAR) NOT NULL,
--	CONTENT CLOB NULL,
--	VIEW_COUNT NUMBER(8,0) DEFAULT 0 NOT NULL,
--	WRITE_DATE DATE NOT NULL,
--	LATEST_MODIFY_DATE DATE NULL,
--	CONSTRAINT BOARD_PK PRIMARY KEY (ID)
--)
--TABLESPACE USERS;
--COMMENT ON TABLE BOARD.BOARD IS '게시글의 목록';
--COMMENT ON COLUMN BOARD.BOARD.ID IS '게시글의 아이디 (BO-YYYYMMDD-일련번호(6자리))';
--COMMENT ON COLUMN BOARD.BOARD.TITLE IS '게시글의 제목';
--COMMENT ON COLUMN BOARD.BOARD.CONTENT IS '게시글의 내용';
--COMMENT ON COLUMN BOARD.BOARD.VIEW_COUNT IS '게시글의 조회수';
--COMMENT ON COLUMN BOARD.BOARD.WRITE_DATE IS '게시글을 작성한 날짜와 시간';
--COMMENT ON COLUMN BOARD.BOARD.LATEST_MODIFY_DATE IS '게시글을 마지막으로 수정한 시간';

--REPLY
CREATE TABLE BOARD.REPLY (
	ID VARCHAR2(18 CHAR) NOT NULL,
	BOARD_ID VARCHAR2(18 CHAR) NOT NULL,
	TOP_ID VARCHAR2(18 CHAR) NULL,
	CONTENT CLOB NOT NULL,
	WRITE_DATE DATE NOT NULL,
	CONSTRAINT REPLY_PK PRIMARY KEY (ID)
)
TABLESPACE USERS;
COMMENT ON TABLE BOARD.REPLY IS '게시글의 댓글, 대댓글.';
COMMENT ON COLUMN BOARD.REPLY.ID IS '댓글의 아이디 (RP-YYYYMMDD-일련번호(6자리))';
COMMENT ON COLUMN BOARD.REPLY.BOARD_ID IS '댓글이 작성된 게시글의 아이디 (BO-YYYYMMDD-일련번호(6자리))';
COMMENT ON COLUMN BOARD.REPLY.TOP_ID IS '대댓글의 상위 댓글 아이디 (RP-YYYYMMDD-일련번호(6자리))';
COMMENT ON COLUMN BOARD.REPLY.CONTENT IS '댓글의 내용';
COMMENT ON COLUMN BOARD.REPLY.WRITE_DATE IS '댓글을 작성한 날짜와 시간';
