---- 추가 문제
-- 1. 부서아이디별 사원의 평균연봉을 조회한다. 12
SELECT AVG(SALARY) AS DEPT_AVG_SALARY
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID 
;
-- 2. 직무아이디별 사원의 최고연봉을 조회한다. 19
SELECT MAX_SALARY 
  FROM JOBS
;
-- 3. 인센티브를 안받는 사원의 모든 정보를 조회한다. 35
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL
;
-- 4. 인센티브를 받는 사원의 부서아이디를 중복없이 조회한다. 1
SELECT DISTINCT DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL
   AND DEPARTMENT_ID IS NOT NULL
;
-- 5. 인센티브를 받는 사원의 직무아이디를 중복없이 조회한다. 2
SELECT DISTINCT JOB_ID 
  FROM EMPLOYEES
 WHERE JOB_ID IS NOT NULL
   AND COMMISSION_PCT IS NOT NULL
;
-- 6. 사원이 있는 부서의 지역아이디를 조회한다. 11
SELECT DISTINCT LOCATION_ID 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID 
 						   FROM EMPLOYEES
 						  WHERE EMPLOYEE_ID IS NOT NULL)
;
-- 7. Seattle에 존재하는 부서번호를 조회한다. 21
SELECT DEPARTMENT_ID
  FROM DEPARTMENTS
 WHERE LOCATION_ID = (SELECT LOCATION_ID
 						FROM LOCATIONS
 					   WHERE CITY = 'Seattle')
;
-- 8. 사원이 한명도 없는 도시를 조회한다. 16
SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID NOT IN (SELECT LOCATION_ID 
 							 FROM DEPARTMENTS
 					   		WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
 					   								  FROM EMPLOYEES))
;
-- 9. 사원이 한명이라도 있는 도시를 조회한다. 7
SELECT CITY
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT LOCATION_ID 
 						 FROM DEPARTMENTS
 					   	WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
 					   							  FROM EMPLOYEES))
;
-- 10. 모든 사원의 정보를 연봉으로 오름차순 정렬하여 조회한다. 107
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 ORDER BY SALARY
;
-- 11. 모든 사원의 사원번호, 이름, 성, 연봉, 인센티브를 포함한 연봉 정보를 조회한다. 107
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , SALARY
	 , CASE WHEN COMMISSION_PCT IS NULL THEN SALARY
	   ELSE ((SALARY * COMMISSION_PCT) + SALARY) END AS "인센티브 연봉"
	 , (NVL(SALARY * COMMISSION_PCT, 0) + SALARY) AS "인센티브 연봉2"
  FROM EMPLOYEES
; 
-- 12. 2003년에 입사한 사원은 몇 명인지 조회한다. 1
SELECT COUNT(EMPLOYEE_ID)
  FROM EMPLOYEES
 WHERE HIRE_DATE BETWEEN TO_DATE('20030101', 'YYYY-MM-DD') AND TO_DATE('20031231', 'YYYY-MM-DD')
;
-- 13. 113번 사원의 상사의 모든 정보를 조회한다. 1
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = (SELECT MANAGER_ID 
 						FROM EMPLOYEES
 					   WHERE EMPLOYEE_ID = 113)
;
-- 14. 모든 부서의 부서장의 모든 사원 정보를 조회한다. 11
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID
 						FROM DEPARTMENTS)
;
-- 15. 사원의 이름이 7자리인 사원의 모든 정보를 조회한다. 23
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES 
 WHERE FIRST_NAME LIKE '_______'
;
-- 16. 사원의 이메일이 6자리인 사원의 모든 정보를 조회한다. 25
SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME
	 , EMAIL
	 , PHONE_NUMBER
	 , HIRE_DATE
	 , JOB_ID
	 , SALARY
	 , COMMISSION_PCT
	 , MANAGER_ID
	 , DEPARTMENT_ID
  FROM EMPLOYEES 
 WHERE EMAIL LIKE '______'
;

--최고 월급을 받는 사원들의 사원 번호와 월급 조회
SELECT E.EMPLOYEE_ID 
	 , E.SALARY 
  FROM EMPLOYEES E
 WHERE E.SALARY = (SELECT MAX(SALARY)
 					 FROM EMPLOYEES)	
;