INSERT INTO BOARD 
 (ID
, TITLE
, CONTENT
, WRITE_DATE) VALUES 
 ('BO-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_BOARD_PK.NEXTVAL, 6, '0')
, ''
, ''
, SYSDATE);

UPDATE BOARD                   
   SET TITLE = '수정된 제목'
     , CONTENT = '수정된 내용'
     , LATEST_MODIFY_DATE = SYSDATE
 WHERE ID = 'BO-20260303-000001';


DELETE
  FROM BOARD
 WHERE ID = ''
;

SELECT ID
	 , TITLE
	 , CONTENT
	 , VIEW_COUNT
	 , TO_CHAR(WRITE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS WRITE_DATE 
	 , TO_CHAR(LATEST_MODIFY_DATE, 'YYYY-MM-DD HH24:MI:SS') AS LATEST_MODIFY_DATE 
  FROM BOARD
 WHERE ID = 'BO-20260303-000002'
;

INSERT INTO REPLY
 (ID
, BOARD_ID
, CONTENT
, WRITE_DATE) VALUES
 ('RP-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_REPLY_PK.NEXTVAL, 6, '0')
, 'BO-20260303-000001'
, '새로운 댓글입니다'
, SYSDATE)
;
SELECT ID
  FROM REPLY
 WHERE ID = 'RP-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || (SELECT LPAD(SEQ_REPLY_PK.CURRVAL, 6, '0')
  														 FROM DUAL)
;
SELECT ID
  FROM REPLY
 WHERE ID = LPAD(SEQ_REPLY_PK.CURRVAL, 6, '0')
;
INSERT INTO REPLY
 (ID
, BOARD_ID
, TOP_ID
, CONTENT
, WRITE_DATE) VALUES
 ('RP-' || TO_CHAR(SYSDATE, 'YYYYMMDD-') || LPAD(SEQ_REPLY_PK.NEXTVAL, 6, '0')
, ''
, ''
, ''
, SYSDATE)
;

--댓글 전체조회
 SELECT ID
 	  , BOARD_ID
 	  , TOP_ID
 	  , CONTENT
 	  , WRITE_DATE
   FROM REPLY
  START WITH TOP_ID IS NULL
CONNECT BY PRIOR ID = TOP_ID
			 
;
--댓글 하나 조회
SELECT ID
	 , BOARD_ID
	 , TOP_ID
	 , CONTENT
	 , WRITE_DATE
  FROM REPLY
 WHERE ID = ?
;
--대댓글 전체 조회
 SELECT ID
	  , BOARD_ID
	  , TOP_ID
	  , CONTENT
	  , WRITE_DATE
   FROM REPLY
  WHERE LEVEL != 1
  START WITH TOP_ID IS NULL
CONNECT BY PRIOR ID = TOP_ID
;
--댓글 수정
UPDATE REPLY
   SET CONTENT = ?
     , WRITE_DATE = SYSDATE
 WHERE ID = ?
;
--댓글 삭제
DELETE
  FROM REPLY
 WHERE ID = ?
;