-- 1. 100번 사원의 모든 부하직원을 계층조회한다. 107
 SELECT LEVEL
 	  , E.EMPLOYEE_ID 
   FROM EMPLOYEES E
  START WITH E.EMPLOYEE_ID = 100
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID
  ORDER BY LEVEL
;
-- 2. 113번 사원의 모든 상사를 계층조회한다. 4
 SELECT LEVEL
 	  , E.EMPLOYEE_ID 
   FROM EMPLOYEES E
  START WITH E.EMPLOYEE_ID = 113
CONNECT BY PRIOR E.MANAGER_ID = E.EMPLOYEE_ID
  ORDER BY LEVEL
;
-- 3. IT 부서장의 모든 부하직원을 계층조회한다. 5
 SELECT LEVEL
 	  , E.EMPLOYEE_ID 
   FROM EMPLOYEES E
  START WITH E.EMPLOYEE_ID = (SELECT MANAGER_ID
							   FROM DEPARTMENTS
							  WHERE DEPARTMENT_NAME = 'IT')		
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID
;
-- 4. 부서장들의 부하직원을 계층조회한다. 147
SELECT LEVEL
 	  , E.EMPLOYEE_ID 
   FROM EMPLOYEES E
  START WITH E.EMPLOYEE_ID IN (SELECT MANAGER_ID
							    FROM DEPARTMENTS)		
CONNECT BY PRIOR E.EMPLOYEE_ID = E.MANAGER_ID
;
-- 5. 부서명이 가장 긴 부서에서 근무중인 사원의 모든 정보를 조회한다. 0
SELECT * 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID 
						 FROM (SELECT DEPARTMENT_ID 
						 			, LENGTH(DEPARTMENT_NAME) AS LEN 
								 FROM DEPARTMENTS
								ORDER BY LEN DESC) 
						WHERE ROWNUM = 1)
 ;
-- 6. 2002년부터 2006년까지 입사한 사원은 몇 명인지 연도별로 조회한다. 5
SELECT HIRE_YEAR
	 , COUNT(EMPLOYEE_ID )
  FROM (SELECT EMPLOYEE_ID 
			 , TO_CHAR(HIRE_DATE, 'YYYY') AS HIRE_YEAR
		  FROM EMPLOYEES
		 WHERE HIRE_DATE >= TO_DATE('20020101', 'YYYY-MM-DD')
		   AND HIRE_DATE <= TO_DATE('20061231', 'YYYY-MM-DD'))
 GROUP BY HIRE_YEAR
 ORDER BY HIRE_YEAR
;
-- 7. 입사일이 가장 빠른 사원 5명의 이름과 입사일을 조회한다. 5
SELECT FIRST_NAME ||
	   ' ' ||
	   LAST_NAME
	 , HIRE_DATE
  FROM (SELECT FIRST_NAME
			 , LAST_NAME
			 , HIRE_DATE
		  FROM EMPLOYEES
		 ORDER BY HIRE_DATE DESC)
 WHERE ROWNUM <= 5
;
-- 8. 커미션을 받는 사원들의 이름과 커미션을 조회한다. 단, 커미션이 가장 높은 사원 3명은 제외한다. 32
SELECT FIRST_NAME ||
	   ' ' ||
	   LAST_NAME AS NAME
	 , COMMISSION_PCT
  FROM (SELECT FIRST_NAME
			 , LAST_NAME
			 , COMMISSION_PCT
			 , ROWNUM AS RN
		  FROM (SELECT FIRST_NAME
					 , LAST_NAME
					 , COMMISSION_PCT
				  FROM EMPLOYEES
				 WHERE COMMISSION_PCT IS NOT NULL
				 ORDER BY COMMISSION_PCT DESC))
 WHERE RN >= 4
;