-- MV-20260227-000001 영화의 영화 정보, 
--장르 정보, 
--출연진 정보, 
--제작진 정보를 출력
SELECT MOVIE_ID
	 , POSTER_URL
	 , TITLE
	 , MOVIE_RATING
	 , OPEN_DATE
	 , OPEN_COUNTRY
	 , RUNNING_TIME
	 , INTRODUCE
	 , SYNOPSIS
	 , ORIGNAL_TITLE
	 , STATE
	 , LANGUAGE
	 , BUDGET
	 , PROFIT
  FROM MOVIES
 WHERE MOVIE_ID = 'MV-20260227-000001'
; 
SELECT CATEGORY_ID
  FROM GENRE
 WHERE MOVIE_ID = 'MV-20260227-000001'
;
SELECT CATEGORY_NAME 
  FROM CATEGORIES
 WHERE CATEGORY_ID IN (SELECT DISTINCT CATEGORY_ID
					     FROM GENRE
					    WHERE MOVIE_ID = ?)
;
SELECT * 
  FROM PRODUCERS
;
SELECT *
  FROM MAKE
 WHERE MOVIE_ID = 'MV-20260227-000001'
;


SELECT P.*
	 , M.*
  FROM PRODUCERS P
 INNER JOIN (SELECT PRODUCER_ID
 				  , PRODUCER_PART 
 				  , PRODUCER_ROLE 
			   FROM MAKE
			  WHERE MOVIE_ID = 'MV-20260227-000001') M
    ON P.PRODUCER_ID = M.PRODUCER_ID

-- WHERE PRODUCER_ID IN 
 
;

SELECT M.MAKE_ID
	 , M.MOVIE_ID
	 , M.PRODUCER_ID
	 , M.PRODUCER_ROLE
	 , M.PRODUCER_PART
	 , P.PRODUCER_NAME 
  FROM MAKE M
 INNER JOIN PRODUCERS P
    ON M.PRODUCER_ID = P.PRODUCER_ID 
   AND MOVIE_ID = ?
;
SELECT PRODUCER_ID 
  FROM PRODUCERS
;
SELECT * 
  FROM MAKE
 WHERE MOVIE_ID = 'MV-20260227-000001'
;

SELECT F.FILMOGRAPHY_ID
	 , F.MOVIE_ID
	 , F.ACTOR_ID
	 , F.ACTOR_ROLE
	 , A.ACTOR_NAME 
  FROM FILMOGRAPHY F
 INNER JOIN ACTORS A
    ON F.ACTOR_ID = A.ACTOR_ID 
   AND F.MOVIE_ID = ?
;
SELECT CATEGORY_NAME
  FROM CATEGORIES
 WHERE CATEGORY_ID IN (SELECT DISTINCT CATEGORY_ID
					     	FROM GENRE
					       WHERE MOVIE_ID = 'MV-20260227-000001')       
;

SELECT *
  FROM GENRE G
 INNER JOIN 
-- WHERE MOVIE_ID = 'MV-20260227-000001'
;					       




















