-- DROP USER TMDB;

CREATE USER TMDB
-- IDENTIFIED BY <password>
;

CREATE TABLE "TMDB"."ACTORS" 
   (	"ACTOR_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"ACTOR_NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"PROFILE_PIC" VARCHAR2(2048 CHAR), 
	 CONSTRAINT "PK_ACTORS" PRIMARY KEY ("ACTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN TMDB.ACTORS.ACTOR_ID IS 'AC-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "TMDB"."CATEGORIES" 
   (	"CATEGORY_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"CATEGORY_NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CATEGORIES" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN TMDB.CATEGORIES.CATEGORY_ID IS 'CT-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "TMDB"."FILMOGRAPHY" 
   (	"FILMOGRAPHY_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"MOVIE_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"ACTOR_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"ACTOR_ROLE" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PK_FILMOGRAPHY" PRIMARY KEY ("FILMOGRAPHY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN TMDB.FILMOGRAPHY.FILMOGRAPHY_ID IS 'FL-YYYYMMDD-SEQUENCE(6)';
COMMENT ON COLUMN TMDB.FILMOGRAPHY.MOVIE_ID IS 'MV-YYYYMMDD-SEQUENCE(6)';
COMMENT ON COLUMN TMDB.FILMOGRAPHY.ACTOR_ID IS 'AC-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "TMDB"."GENRE" 
   (	"GENRE_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"MOVIE_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"CATEGORY_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PK_GENRE" PRIMARY KEY ("GENRE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN TMDB.GENRE.GENRE_ID IS 'GE-YYYYMMDD-SEQUENCE(6)';
COMMENT ON COLUMN TMDB.GENRE.MOVIE_ID IS 'MV-YYYYMMDD-SEQUENCE(6)';
COMMENT ON COLUMN TMDB.GENRE.CATEGORY_ID IS 'CT-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "TMDB"."MAKE" 
   (	"MAKE_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"MOVIE_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"PRODUCER_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"PRODUCER_ROLE" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"PRODUCER_PART" VARCHAR2(40 CHAR), 
	 CONSTRAINT "PK_MAKE" PRIMARY KEY ("MAKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN TMDB.MAKE.MAKE_ID IS 'MK-YYYYMMDD-SEQUENCE(6)';
COMMENT ON COLUMN TMDB.MAKE.MOVIE_ID IS 'MV-YYYYMMDD-SEQUENCE(6)';
COMMENT ON COLUMN TMDB.MAKE.PRODUCER_ID IS 'PD-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "TMDB"."MOVIES" 
   (	"MOVIE_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"POSTER_URL" VARCHAR2(2048 CHAR) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"MOVIE_RATING" VARCHAR2(3 CHAR), 
	"OPEN_DATE" DATE, 
	"OPEN_COUNTRY" VARCHAR2(2 CHAR), 
	"RUNNING_TIME" NUMBER(4,0), 
	"INTRODUCE" VARCHAR2(60 CHAR), 
	"SYNOPSIS" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"ORIGNAL_TITLE" VARCHAR2(50 CHAR), 
	"STATE" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"LANGUAGE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"BUDGET" NUMBER(11,2), 
	"PROFIT" NUMBER(12,2), 
	 CONSTRAINT "PK_MOVIES" PRIMARY KEY ("MOVIE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN TMDB.MOVIES.MOVIE_ID IS 'MV-YYYYMMDD-SEQUENCE(6)';

CREATE TABLE "TMDB"."PRODUCERS" 
   (	"PRODUCER_ID" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"PRODUCER_NAME" VARCHAR2(40 CHAR), 
	 CONSTRAINT "PK_PRODUCERS" PRIMARY KEY ("PRODUCER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN TMDB.PRODUCERS.PRODUCER_ID IS 'PD-YYYYMMDD-SEQUENCE(6)';

CREATE SEQUENCE TMDB.SEQ_ACTORS_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE CACHE 5 NOORDER ;

CREATE SEQUENCE TMDB.SEQ_CATEGORIES_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE CACHE 5 NOORDER ;

CREATE SEQUENCE TMDB.SEQ_FILMOGRAPHY_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE CACHE 5 NOORDER ;

CREATE SEQUENCE TMDB.SEQ_GENRE_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOCACHE NOORDER ;

CREATE SEQUENCE TMDB.SEQ_MAKE_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE CACHE 5 NOORDER ;

CREATE SEQUENCE TMDB.SEQ_MOVIES_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE CACHE 5 NOORDER ;

CREATE SEQUENCE TMDB.SEQ_PRODUCERS_PK INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE CACHE 5 NOORDER ;