-- 사용자 생성 스크립트

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER SPRING_BOOT IDENTIFIED BY SPRING_BOOT;

ALTER USER SPRING_BOOT DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

ALTER USER SPRING_BOOT TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO SPRING_BOOT;

GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO SPRING_BOOT;

COMMIT;