-- 사용자 생성 스크립트

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER BOARD IDENTIFIED BY BOARD;

ALTER USER BOARD DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

ALTER USER BOARD TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO BOARD;

GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO BOARD;

COMMIT;